### ISSUE TITLE
Add slack invite to homepage

### ISSUE THREAD

**Issue by klieret** [hsf-training/organization#7]

**Comment by wdconinc** [comment]
FYI https://github.com/emedvedev/slackin-extended ? live e.g. at https://slack.spack.io . I'm not sure if we could run this inside a gh-pages.

**Comment by klieret** [comment]
This is very cool!  But the way I understand it, we need an actual server for that, right? (I only took a quick look so far and didn't find much explanation/documentation)  Do you know who set this up for spack?

**Comment by klieret** [comment]
The deploy to Heroku seems pretty easy, but the question is of course if the free account is enough there, so let's see what the Spack group uses :)

**Comment by klieret** [comment]
For now, I have simply created a normal tile for the homepage, while we figure this out:

![image](https://user-images.githubusercontent.com/13602468/168559452-d4a1516b-aa00-46d4-8587-668f0941f781.png)
